# Generated by Django 4.2.7 on 2023-11-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcourse',
            name='golfcourseimage',
            field=models.ImageField(blank=True, null=True, upload_to='golf_course_images/'),
        ),
    ]
